### ISSUE TITLE
Auto-detect available sources

### ISSUE THREAD

**Issue by Nowaker** [filiparag/wikiman#10]
The application shouldn't need a config to work. Or even with a config present, a missing `sources` clause in the config should make Wikiman simply autodetect sources.

**Comment by filiparag** [comment]
This feature was present in earlier version, but due to performance issues, it was removed in commit [a801157ca94143128967a9fcc8f1efb7168f9ad8](https://github.com/filiparag/wikiman/tree/a801157ca94143128967a9fcc8f1efb7168f9ad8).

In the meantime, source module structure was improved, so adding it back shouldn't be a problem.

**Comment by filiparag** [comment]
Autodetect feature is implemented in commit [63d620d](https://github.com/filiparag/wikiman/commit/63d620d5009e057ffc0862173d48988144a1226e).

Thanks for the idea!

Configuration file `/etc/wikiman.conf` is installed by default, so if the user doesn't remove it manually, there will be no warning.
