### ISSUE TITLE
Unnecessary dependencies on rpm package on v2.11-1.fc32

### ISSUE THREAD

**Issue by deuzene** [filiparag/wikiman#21]
The rpm package requires `zsh` and `fish`.

**Comment by filiparag** [comment]
By looking at RedHat's documentation, I found [this article](https://access.redhat.com/solutions/1326853).
Wikiman comes bundled with shell widgets for `bash`, `fish` and `zsh`. When running `rpm-build`, it detects these files and thinks that they lacks dependencies.

I added `AutoReq: n` to the spec file and the issue seems to be fixed in version [2.11.1}(https://github.com/filiparag/wikiman/releases/tag/2.11.1).
