### ISSUE TITLE
about sources

### ISSUE THREAD

**Issue by asdf8dfafjk** [filiparag/wikiman#32]
I cannot help but think that source data installation is needlessly complex. 

Ideally there should be a default path list (/usr/share/wikiman, ~/.local/share/wikiman) that could be overriden using a config and the download procedure should be a subcommand of wikiman that would try to write in the aforementioned path list sequentially. (So a sudo would allow me to write globally).

**Comment by filiparag** [comment]
Hi,

The source data installation was constructed like this because the only original data source was Arch Wiki which was installable by the system's package manager as a shared database.

The other ones were just appended afterwards, and having the download code separate from the utility means it always knows which snapshots are the latest. For instance, due to having to make a very hacky snapshotting tool for the Genoo Wiki, it is updated less often than the rest. Updating data sources would require either the change of hardcoded links in the utility, or a way to look up links to the latest snapshots.

The idea you are proposing is sound and I like it; it only needs to fix the aforementioned problem. Would you like to write it yourself as a Pull request? I am currently busy with other things, so implementing it might take a while.

**Comment by asdf8dfafjk** [comment]
Sorry I don't have context into the code and the benefit would not be worth the extra boot-up time :| 

Thanks for the great software though!
